version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./lms-backend
    ports:
      - "5000:5000"
    volumes:
      - ./lms-backend:/app
      - /app/node_modules  # prevent overwriting node_modules inside container
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/lms

  frontend:
    build:
      context: ./lms-frontend
    ports:
      - "4200:80"
    restart: always

volumes:
  mongo-data:
